# Generated by Django 3.1 on 2020-08-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialusersearch',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
