# Generated by Django 3.1 on 2020-08-12 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200811_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_link', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.socialusersearch')),
            ],
            options={
                'db_table': 'tbl_google_search',
                'unique_together': {('username', 'google_link')},
            },
        ),
    ]
