# Generated by Django 3.1 on 2020-08-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_googlesearchmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesearchmodel',
            name='site_title',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
