# Generated by Django 3.1 on 2020-08-17 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_googlesearchmodel_site_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantUsernameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=255)),
                ('website_url', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.socialusersearch')),
            ],
            options={
                'db_table': 'tbl_instant_username',
                'unique_together': {('username', 'website_name')},
            },
        ),
    ]
